### ISSUE TITLE
Open links to external websites in new tabs

### ISSUE THREAD

**Issue by b-m-f** [b-m-f/freelytics#23]
Currently the links to the blog articles open in the same page.

These could be openen in a new Tab. Any thoughts?

**Comment by mr-islam** [comment]
Definitely, should open in a new tab. 

Since the links are in the left sidebar, it can be misleading and make the user expect navigation within the current website, instead of a link to another website.

Perhaps an icon like [these](https://thenounproject.com/term/open-new-tab/) can make it clear that the links will open in a new tab, and go to a new website?

**Comment by b-m-f** [comment]
@mr-islam Thats a good idea. Thanks! I think this is how it should be done for now.

At some point it might be possible to put some markdown in the repository and just render the tutorials directly.
